### ISSUE TITLE
Navigating back to the previous screen results in ConcurrentModificationError

### ISSUE THREAD

**Issue by viju85** [mchome/flutter_advanced_networkimage#11]
I used TransitionToImage widget as below:

```dart
new Stack(
      alignment: Alignment.center,
      children: <Widget>[
        new Container(
          child: new TransitionToImage(
              new AdvancedNetworkImage(
                      movieGridUtil.getUrlFromPath(
                          widget.movie.backdrop_path, MovieGridImageTypes.BACKDROP),
                      useMemoryCache: false,
                      useDiskCache: true),
            placeholder: new CircularProgressIndicator(),
          ),
        ),
        new Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            videoIcon
          ],
        )
      ],
    );
```

But, when I tap back to navigate to my previous screen, I get the below exception:
```
I/flutter (20648): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20648): The following ConcurrentModificationError was thrown while finalizing the widget tree:
I/flutter (20648): Concurrent modification during iteration: Instance(length:0) of '_GrowableList'.
I/flutter (20648): 
I/flutter (20648): When the exception was thrown, this was the stack:
I/flutter (20648): #0      List.forEach (dart:core/runtime/libgrowable_array.dart:275:36)
I/flutter (20648): #1      _TransitionToImageState.dispose (package:flutter_advanced_networkimage/transition_to_image.dart:114:22)
I/flutter (20648): #2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3821:12)
I/flutter (20648): #3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
I/flutter (20648): #4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #5      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #11     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
I/flutter (20648): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #14     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
I/flutter (20648): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
I/flutter (20648): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #29     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #53     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #77     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
I/flutter (20648): #78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #89     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #95     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #115    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #116    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #118    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #119    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #120    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #121    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #122    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #123    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #124    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #125    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #126    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #127    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #128    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #129    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #130    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #131    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #132    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #133    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #134    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #135    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #136    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #137    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #138    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #139    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #140    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #141    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #142    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #143    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #144    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #145    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #146    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #147    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #148    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #149    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #150    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #151    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #152    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #153    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #154    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #155    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #156    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #157    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #158    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (20648): #159    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #160    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #161    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #162    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #163    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #164    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #165    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #166    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (20648): #167    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (20648): #168    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (20648): #169    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (20648): #170    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
I/flutter (20648): #171    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2328:27)
I/flutter (20648): #172    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2160:15)
I/flutter (20648): #173    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2327:7)
I/flutter (20648): #174    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:628:18)
I/flutter (20648): #175    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (20648): #176    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (20648): #177    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (20648): #178    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (20648): #179    _invoke (dart:ui/hooks.dart:120:13)
I/flutter (20648): #180    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (20648): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Ajit121** [comment]
Having the same issue while using this in list item
