### ISSUE TITLE
Cant "compile": InvalidType doesn't have nullability

### ISSUE THREAD

**Issue by ScholliYT** [mchome/flutter_advanced_networkimage#142]
I'm trying to setup something like this: https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54

However, if I run `dart test_driver/main_test.dart` I'm getting the following error. Seems to be related to this package.
Using Flutter version: `Channel master, v1.14.4-pre.17` (also tried current stable and others)
```
Crash when compiling file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.6.3/lib/src/provider/flutter_advanced_networkimage.dart,
at character offset 5759:
InvalidType doesn't have nullability
#0      InvalidType.nullability (package:kernel/ast.dart:5637:34)
#1      computeNullability (package:kernel/src/future_or.dart:66:15)
#2      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:348:11)
#3      TypeConstraintGatherer.trySubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:110:20)
#4      TypeSchemaEnvironment.inferGenericFunctionOrType (package:front_end/src/fasta/type_inference/type_schema_environment.dart:223:16)
#5      TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1962:29)
#6      TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1833:12)
#7      InferenceVisitor.visitFactoryConstructorInvocationJudgment (package:front_end/src/fasta/kernel/inference_visitor.dart:707:38)
#8      FactoryConstructorInvocationJudgment.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:584:20)
#9      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1751:27)
#10     InferenceVisitor.visitReturnStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:4705:61)
#11     ReturnStatement.accept (package:kernel/ast.dart:5036:43)
#12     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:2895:24)
#13     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:299:20)
#14     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:320:30)
#15     Block.accept (package:kernel/ast.dart:4597:43)
#16     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:2895:24)
#17     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1796:39)
#18     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:955:28)
#19     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:908:14)
#20     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:941:7)
#21     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:668:5)
#22     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3490:20)
#23     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3251:15)
#24     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2984:15)
#25     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#26     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#27     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#28     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#29     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#30     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:334:14)
<asynchronous suspension>
#31     Loader.buildBodies (package:front_end/src/fasta/loader.dart:247:15)
<asynchronous suspension>
#32     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:326:20)
#33     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#34     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:324:12)
#35     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:660:28)
<asynchronous suspension>
#36     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#37     new Future.sync (dart:async/future.dart:224:31)
#38     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#39     _rootRun (dart:async/zone.dart:1126:13)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _runZoned (dart:async/zone.dart:1518:10)
#42     runZoned (dart:async/zone.dart:1465:12)
#43     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#44     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:169:20)
#45     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#46     IncrementalCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:302:39)
#47     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:163:45)
#48     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#49     _rootRun (dart:async/zone.dart:1122:38)
#50     _CustomZone.run (dart:async/zone.dart:1023:19)
#51     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#52     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#53     _rootRun (dart:async/zone.dart:1126:13)
#54     _CustomZone.run (dart:async/zone.dart:1023:19)
#55     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#56     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#57     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#58     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:946:7)
#1      DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:668:5)
#2      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3490:20)
#3      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3251:15)
#4      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2984:15)
#5      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#6      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#8      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#9      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:334:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:247:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:326:20)
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:324:12)
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:660:28)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _runZoned (dart:async/zone.dart:1518:10)
#22     runZoned (dart:async/zone.dart:1465:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:169:20)
#25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#26     IncrementalCompilerWrapper.compileInternal (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:302:39)
#27     Compiler.compile.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:163:45)
#28     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#29     _rootRun (dart:async/zone.dart:1122:38)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by ScholliYT** [comment]
I'll try to provide an small example soon
