### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by dasmikko** [mchome/flutter_advanced_networkimage#52]
Hi, would it be possible to add SVG file support?

I'm currently using [this](https://pub.dartlang.org/packages/flutter_svg) library to display SVG images over network, but it doesn't seem to cache the images, so I was hoping your awesome library to add SVG support.

**Comment by mchome** [comment]
Looks cool, i will try to integrate flutter_svg.

**Comment by dasmikko** [comment]
Awesome! Looking forward to this.

**Comment by mchome** [comment]
Try `0.4.0-alpha`, it's better upgrade to flutter v1.1.7.

**Comment by dasmikko** [comment]
Nice, I'll give it a try asap.

**Comment by dasmikko** [comment]
Can't seem to get it working.

Svg images are blank.

![image](https://user-images.githubusercontent.com/4254869/52040746-a9e0f780-2538-11e9-8ecb-d33f260dc927.png)

the `icon` variable contains the url of the svg

And i'm gettings these exeptions:

```
E/flutter (19507): NoSuchMethodError: The method 'toDouble' was called on null.
E/flutter (19507): Receiver: null
E/flutter (19507): Tried calling: toDouble()
E/flutter (19507): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (19507): #1      int./ (dart:core/runtime/libintegers.dart:24:36)
E/flutter (19507): #2      _loadFromRemote.<anonymous closure>.<anonymous closure> 
package:flutter_advanced_networkimage/src/flutter_advanced_networksvg.dart:273
E/flutter (19507): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (19507): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (19507): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter (19507): #6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
E/flutter (19507): #7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter (19507): #8      _HandlerEventSink.add (dart:async/stream_transformers.dart:238:13)
E/flutter (19507): #9      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
E/flutter (19507): #10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (19507): #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (19507): #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter (19507): #13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter (19507): #14     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
E/flutter (19507): #15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter (19507): #16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (19507): #17     CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
E/flutter (19507): #18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (19507): #19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (19507): #20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter (19507): #21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
E/flutter (19507): #22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter (19507): #23     _ByteAdapterSink.add (dart:convert/byte_conversion.dart:58:11)
E/flutter (19507): #24     _FilterSink.addSlice (dart:io/data_transformer.dart:611:15)
E/flutter (19507): #25     _FilterSink.add (dart:io/data_transformer.dart:596:5)
E/flutter (19507): #26     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
E/flutter (19507): #27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
E/flutter (19507): #28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (19507): #29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (19507): #30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter (19507): #31     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter (19507): #32     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
E/flutter (19507): #33     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter (19507): #34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (19507): #35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (19507): #36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter (19507): #37     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
E/flutter (19507): #38     _StreamController._add (dart:async/stream_controller.dart:640:7)
E/flutter (19507): #39     _StreamController.add (dart:async/stream_controller.dart:586:5)
E/flutter (19507): #40     _HttpParser._doParse (dart:_http/http_parser.dart:767:27)
E/flutter (19507): #41     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
E/flutter (19507): #42     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
E/flutter (19507): #43     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (19507): #44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (19507): #45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter (19507): #46     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
E/flutter (19507): #47     _StreamController._add (dart:async/stream_controller.dart:640:7)
E/flutter (19507): #48     _StreamController.add (dart:async/stream_controller.dart:586:5)
E/flutter (19507): #49     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)
E/flutter (19507): #50
```

**Comment by mchome** [comment]
Commit `05ef1a92f091986ce67a51ea2c202c30f487687d` should fix this.

**Comment by dasmikko** [comment]
Works now! 👍
