### ISSUE TITLE
Error: The method 'toDouble' was called on null.

### ISSUE THREAD

**Issue by nemoryoliver** [mchome/flutter_advanced_networkimage#58]
I'm using the latest version with this dependency: **flutter_advanced_networkimage: any**

Getting this error on some images I am trying to load.

### Error

```
[VERBOSE-2:shell.cc(186)] Dart Error: Unhandled exception:
NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      int./ (dart:core/runtime/libintegers.dart:24:36)
#2      _loadFromRemote.<anonymous closure>.<anonymous closure> (package:flutter_advanced_networkimage/src/flutter_advanced_networkimage.dart:270:39)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#8      _HandlerEventSink.add (dart:async/stream_transformers.dart:238:13)
#9      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#10  <…>

```

### Flutter Doctor

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.8 at /Users/nemory/Development/flutter
    • Framework revision 985ccb6d14 (4 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nemory/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.1.1 (API 25) (emulator)
    • iPhone XS Max             • 39AC65C7-4F9F-454F-B1B5-3376EE04BCBF • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by mchome** [comment]
Try commit `90422791081984fec75a4db38f453410a30135e9`.

**Comment by nemoryoliver** [comment]
Sorry for the dumb question. but how to do I specifically load the package with the commit?

**Comment by mchome** [comment]
ref: https://www.dartlang.org/tools/pub/dependencies#git-packages
```yml
dependencies:
  kittens:
    git:
      url: git://github.com/mchome/flutter_advanced_networkimage.git
      path: 90422791081984fec75a4db38f453410a30135e9
```

**Comment by nemoryoliver** [comment]
> ref: https://www.dartlang.org/tools/pub/dependencies#git-packages
> 
> ```yaml
> dependencies:
>   flutter_advanced_networkimage:
>     git:
>       url: git://github.com/mchome/flutter_advanced_networkimage.git
>       path: 90422791081984fec75a4db38f453410a30135e9
> ```

Thank you very much!!!! I am so happy to use your package! it's very useful. I really appreciate your time and effort building this and open sourcing it. can't wait for the next release :)

**Comment by nemoryoliver** [comment]
Sorry, just tried now and failed. did I do something wrong? 

**Error**

`Could not find a file named "90422791081984fec75a4db38f453410a30135e9/pubspec.yaml" in git://github.com/mchome/flutter_advanced_networkimage.git 90422791081984fec75a4db38f453410a30135e9.`

**Comment by mchome** [comment]
My copy mistake, updated. :laughing:

**Comment by mchome** [comment]
`0.4.2` released.

**Comment by nemoryoliver** [comment]
> `0.4.2` released.

amazing!!!! thanks a lot!! just upgraded

**Comment by mchome** [comment]
I am sorry, just test it, not working actually, my bad.

**Comment by nemoryoliver** [comment]
> I am sorry, just test it, not working actually, my bad.
> I should create test for it.

oh it's okay... haven't tested it too myself.. gotta go now.. thanks a lot for your great work

**Comment by mchome** [comment]
`0.4.3` fixed this.
