### ISSUE TITLE
Dart 2 issue

### ISSUE THREAD

**Issue by romaluca** [mchome/flutter_advanced_networkimage#6]
I enabled dart 2 and now i have this error: 
```

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building TransitionToImage(dirty, state:
_TransitionToImageState#0fe66(tickers: tracking 1 ticker)):
type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
_AnimatedEvaluation is from package:flutter/src/animation/tween.dart
Animation is from package:flutter/src/animation/animation.dart
double is from dart:core

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#0      _TransitionToImageState.build (package:flutter_advanced_networkimage/transition_to_image.dart:136:33)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#25     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3938:11)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4738:32)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4738:32)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#49     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3938:11)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#51     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4738:32)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#100    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#101    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#108    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#127    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#132    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4738:32)
#133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
page: 1
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#142    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#148    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#152    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#156    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#157    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#158    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#159    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#162    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#168    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#178    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#181    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#190    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#194    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#195    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#196    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#197    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#198    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#202    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#203    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#204    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#205    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#209    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#210    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#211    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#212    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#214    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4420:32)
#215    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4748:17)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#217    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#220    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#221    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#223    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#224    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#225    ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#226    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#227    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4640:14)
#228    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#230    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#231    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#232    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#233    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4640:14)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#235    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4640:14)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#238    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#239    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
#240    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
#241    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#242    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#243    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#244    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
#245    _invoke (dart:ui/hooks.dart:120:13)
#246    _drawFrame (dart:ui/hooks.dart:109:3)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
Another exception was thrown: type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
Another exception was thrown: type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
Another exception was thrown: type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
Another exception was thrown: type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
Another exception was thrown: type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
Another exception was thrown: type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
Another exception was thrown: type '_AnimatedEvaluation' is not a subtype of type 'Animation<double>' where
```

**Comment by mchome** [comment]
Hey, can you provide some example codes, i have no idea with this.

**Comment by mchome** [comment]
It works well in dart2 preview now :)

**Comment by romaluca** [comment]
Thanks! 
Unfortunately, I have another issue in dart:
https://github.com/dart-lang/sdk/issues/32553#issuecomment-376575146
so i can't try it :(

**Comment by romaluca** [comment]
Hi i update flutter and now i receive this error:

```
Incompatible version constraints on quiver:
- flutter_advanced_networkimage 0.2.2 depends on version >=0.28.0 <0.29.0
```

**Comment by mchome** [comment]
I have upgraded the dependencies in `0.2.2+1`.
