### ISSUE TITLE
Can not load image url 

### ISSUE THREAD

**Issue by jinfagang** [mchome/flutter_advanced_networkimage#75]
My Image got this error:

```
The following _Exception was thrown resolving an image codec:
I/flutter ( 2022): Exception: Failed to load http://loliloli.pro:9000/images/chat/13ce919034328865b238f731e5bff0ba.
I/flutter ( 2022): 
I/flutter ( 2022): When the exception was thrown, this was the stack:
I/flutter ( 2022): #0      AdvancedNetworkImage._loadAsync (package:flutter_advanced_networkimage/src/flutter_advanced_networkimage.dart:227:5)
I/flutter ( 2022): <asynchronous suspension>
I/flutter ( 2022): #1      AdvancedNetworkImage.load (package:flutter_advanced_networkimage/src/flutter_advanced_networkimage.dart:170:14)
I/flutter ( 2022): #2      AdvancedNetworkImage.resolve.<anonymous closure>.<anonymous closure> (package:flutter_advanced_networkimage/src/flutter_advanced_networkimage.dart:153:37)
I/flutter ( 2022): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:157:22)
I/flutter ( 2022): #4      AdvancedNetworkImage.resolve.<anonymous closure> (package:flutter_advanced_networkimage/src/flutter_advanced_networkimage.dart:153:14)
I/flutter ( 2022): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter ( 2022): #6      AdvancedNetworkImage.resolve (package:flutter_advanced_networkimage/src/flutter_advanced_networkimage.dart:146:30)
I/flutter ( 2022): #7      DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:239:55)
I/flutter ( 2022): #8      _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:414:19)
I/flutter ( 2022): #9      _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:432:5)
I/flutter ( 2022): #10     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1955:16)
I/flutter ( 2022): #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter ( 2022): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #16     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 2022): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #19     RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:909:17)
I/flutter ( 2022): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #22     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 2022): #23     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:594:5)
I/flutter ( 2022): #24     RenderStack.paint (package:flutter/src/rendering/stack.dart:602:7)
I/flutter ( 2022): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter ( 2022): #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter ( 2022): #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #33     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 2022): #34     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
I/flutter ( 2022): #35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #37     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 2022): #38     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
I/flutter ( 2022): #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #41     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 2022): #42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter ( 2022): #45     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2435:13)
I/flutter ( 2022): #46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter ( 2022): #49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #50     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 2022): #51     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 2022): #52     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 2022): #53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 2022): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
I/flutter ( 2022): #55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #57     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:557:17)
I/flutter ( 2022): #58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #60     RenderSliverPadding.paint (package:flutter/src/rendering/sliver_padding.dart:314:15)
I/flutter ( 2022): #61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 2022): #63     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:524:17)
I/flutter ( 2022): #64     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter ( 2022): #65     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:394:7)
I/flutter ( 2022): #66     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:515:15)
I/flutter ( 2022): #67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
I/flutter ( 2022): #68     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 2022): #69     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 2022): #70     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:855:29)
I/flutter ( 2022): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:283:19)
I/flutter ( 2022): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:686:13)
I/flutter ( 2022): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 2022): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 2022): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 2022): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 2022): #77     _invoke (dart:ui/hooks.dart:159:13)
I/flutter ( 2022): #78     _drawFrame (dart:ui/hooks.dart:148:3)
D/ViewRootImpl@d296bde[MainActivity]( 2022): ViewPostImeInputStage processPointer 1
I/flutter ( 2022): 
I/flutter ( 2022): Image provider:
I/flutter ( 2022): AdvancedNetworkImage("http://loliloli.pro:9000/images/chat/13ce919034328865b238f731e5bff0ba",scale:
I/flutter ( 2022): 1.0,header: null,useDiskCache: true,retryLimit: 5,retryDuration: 0:00:00.500000,retryDurationFactor:
I/flutter ( 2022): 1.5,timeoutDuration: 0:00:05.000000)
I/flutter ( 2022): Image provider:
I/flutter ( 2022): AdvancedNetworkImage("http://loliloli.pro:9000/images/chat/13ce919034328865b238f731e5bff0ba",scale:
I/flutter ( 2022): 1.0,header: null,useDiskCache: true,retryLimit: 5,retryDuration: 0:00:00.500000,retryDurationFactor:
I/flutter ( 2022): 1.5,timeoutDuration: 0:00:05.000000)
I/flutter ( 2022): ════════════════════════════════════════════
```

http://loliloli.pro:9000/images/chat/13ce919034328865b238f731e5bff0ba this image is actually callable:

![](http://loliloli.pro:9000/images/chat/13ce919034328865b238f731e5bff0ba)

**Comment by mchome** [comment]
Hi @jinfagang , can you have a try on commit `87fba6d83169298c3bfb01e981b790f5a739550b`?

**Comment by mchome** [comment]
`v0.4.10` released.

**Comment by jinfagang** [comment]
@mchome Thanks for your flash speed

**Comment by Smagold** [comment]
@mchome still throws in `v0.4.11`

**Comment by mchome** [comment]
@Smagold Can you please drop some example code here?

**Comment by Smagold** [comment]
@mchome thanks for instant reply! Here's my code:
```
TransitionToImage(
  image: AdvancedNetworkImage(photo.largeUrl, retryLimit: 1, timeoutDuration: Duration(seconds: 30)),
  loadingWidget: Container(color: commonColor, child: Center(child: CircularProgressIndicator(valueColor: new AlwaysStoppedAnimation<Color>(Colors.white)))),
  fit: BoxFit.cover,
)
```

**Comment by mchome** [comment]
@Smagold No error throws here, can you paste your `photo.largeUrl` and error message?

**Comment by Smagold** [comment]
@mchome The exception is: `_Exception (Exception: Failed to load .)`, which implies that image url is empty. I added a check for empty string - it's not empty at all times.
It throws occasionally on every screen where I use `AdvancedNetworkImage`

**Comment by Smagold** [comment]
Also, have to add that I just updated my Flutter version (ran `flutter upgrade`), and updated the plugin to `v0.4.11`. I didn't encounter any exceptions before the upgrade.

**Comment by mchome** [comment]
@Smagold Try `v0.4.12`.

**Comment by flute** [comment]
@mchome still throws in v0.4.13

**Comment by mchome** [comment]
@flute Please open a new issue and post your code.
