### ISSUE TITLE
Buffer was empty error

### ISSUE THREAD

**Issue by romaluca** [mchome/flutter_advanced_networkimage#8]
With the last version of flutter 0.2.9 i'm receiving this error:

```
[VERBOSE-2:codec.cc(76)] InitCodec failed - buffer was empty
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'package:flutter/src/painting/image_stream.dart': Failed assertion: line 362 pos 12: '_codec != null': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart)
#3      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
#7      Future._complete (dart:async/future_impl.dart:467:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#9      AdvancedNetworkImage._loadAsync (package:flutter_advanced_networkimage/flutter_advanced_networkimage.dart)
<asynchronous suspension>
#10     Ad<…>
```

Thanks

**Comment by mchome** [comment]
Sorry for the long wait, this should be fixed now :)
