### ISSUE TITLE
Exception when calling setState on loadedCallback

### ISSUE THREAD

**Issue by erf** [mchome/flutter_advanced_networkimage#84]
I have a `StatefulWidget` with a `TransitionToImage(image: AdvancedNetworkImage...`.

I get an exception when i call `setState` inside `TransitionToImage.loadedCallback`.

Log:
```
Performing hot restart...
Syncing files to device iPhone XR...
Restarted application in 2,937ms.
flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following assertion was thrown when reporting an error to an image listener:
flutter: setState() or markNeedsBuild() called during build.
flutter: This TransitionToImage widget cannot be marked as needing to build because the framework is already
flutter: in the process of building widgets. A widget can be marked as needing to be built during the build
flutter: phase only if one of its ancestors is currently building. This exception is allowed because the
flutter: framework builds parent widgets before children, which means a dirty descendant will always be
flutter: built. Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   TransitionToImage(dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#83f64],
flutter:   Directionality], state: _TransitionToImageState#1a37c(ticker inactive))
flutter: The widget which was currently being built when the offending call was made was:
flutter:   PlaceholderImage
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3497:11)
flutter: #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3523:6)
flutter: #2      State.setState (package:flutter/src/widgets/framework.dart:1138:14)
flutter: #3      _TransitionToImageState._catchBadImage (package:flutter_advanced_networkimage/src/transition_to_image.dart:335:5)
flutter: #4      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:404:24)
flutter: #5      ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:286:9)
flutter: #6      MultiFrameImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:604:11)
flutter: #7      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:160:25)
flutter: #8      _TransitionToImageState._getImage (package:flutter_advanced_networkimage/src/transition_to_image.dart:319:20)
flutter: #9      _TransitionToImageState.didChangeDependencies (package:flutter_advanced_networkimage/src/transition_to_image.dart:227:5)
flutter: #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862:12)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
flutter: #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
flutter: #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #33     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #34     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #38     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #50     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #58     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #62     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #66     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #68     SliverVariableSizeBoxAdaptorElement.updateChild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:170:36)
flutter: #69     SliverVariableSizeBoxAdaptorElement.performRebuild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:130:13)
flutter: #70     SliverVariableSizeBoxAdaptorElement.update (package:flutter_staggered_grid_view/src/widgets/sliver.dart:99:54)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #74     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #78     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #79     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #80     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #96     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #102    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #106    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #116    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #120    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #124    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #130    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #134    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #136    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #137    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #140    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #141    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #144    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #145    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #148    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #149    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #151    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #155    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #157    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #161    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #164    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #165    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #168    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #169    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #173    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #176    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #177    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #181    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #182    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #183    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #184    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
flutter: #185    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #186    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
flutter: #190    _invoke (dart:ui/hooks.dart:209:10)
flutter: #191    _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: setState() or markNeedsBuild() called during build.
```

**Comment by mchome** [comment]
Hi, give me a code snippet to reproduce this issue.

**Comment by erf** [comment]
Here is a minimal example. Press the image to go to the next page, to trigger the Exception. The exception only happens when the image is wrapped in a `Hero` widget. If you try to comment out the `setState` call inside `loadedCallback`, everything is ok. I wanted to set a `isLoaded` attribute after `loadedCallback` was called, so i could recreate the UI with some changes.

```
import 'package:flutter/material.dart';

import 'package:flutter/cupertino.dart';
import 'package:flutter_advanced_networkimage/provider.dart';
import 'package:flutter_advanced_networkimage/transition.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DiscoverPage(),
    );
  }
}

class DiscoverPage extends StatefulWidget {
  DiscoverPage();

  @override
  State<StatefulWidget> createState() {
    return _DiscoverPageState();
  }
}

class _DiscoverPageState extends State<DiscoverPage> {
  var items = [1, 2, 3, 4, 5];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: items.length,
        itemBuilder: (context, index) {
          final id = items[index];
          return GestureDetector(
            onTap: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (context) => ItemDetailPage(id)));
            },
            child: ItemTile(id),
          );
        },
      ),
    );
  }
}

class ItemTile extends StatefulWidget {
  final int id;

  ItemTile(this.id);

  @override
  _ItemTileState createState() => _ItemTileState();
}

class _ItemTileState extends State<ItemTile> {
  bool _imageIsLoaded = false;

  _ItemTileState();

  @override
  Widget build(BuildContext context) {
    return Hero(
      tag: 'id-${widget.id}',
      child: TransitionToImage(
        image: AdvancedNetworkImage(
          'https://www.gstatic.com/webp/gallery/1.jpg',
        ),
        loadedCallback: () {
          setState(() {
            _imageIsLoaded = true;
          });
        },
      ),
    );
  }
}

class ItemDetailPage extends StatefulWidget {
  final int id;

  ItemDetailPage(this.id);

  @override
  _ItemDetailPageState createState() => _ItemDetailPageState();
}

class _ItemDetailPageState extends State<ItemDetailPage> {
  @override
  Widget build(BuildContext context) {
    return Hero(
      tag: 'id-${widget.id}',
      child: TransitionToImage(
        image: AdvancedNetworkImage(
          'https://www.gstatic.com/webp/gallery/1.jpg',
        ),
      ),
    );
  }
}
```

**Comment by mchome** [comment]
Can you use `loadedCallback` in `AdvancedNetworkImage` instead?

**Comment by erf** [comment]
Yes. This seem to work.

**Comment by erf** [comment]
I found a case where this crashes still. If i add a `key`, to the stateful widget, it crashes inside `loadedCallback`, because `mounted` is now false ( most of the time ).

Se example ( notice `loaded` does not show ):
```
import 'package:flutter/material.dart';

import 'package:flutter/cupertino.dart';
import 'package:flutter_advanced_networkimage/provider.dart';
import 'package:flutter_advanced_networkimage/transition.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DiscoverPage(),
    );
  }
}

class DiscoverPage extends StatefulWidget {
  DiscoverPage();

  @override
  State<StatefulWidget> createState() {
    return _DiscoverPageState();
  }
}

class _DiscoverPageState extends State<DiscoverPage> {
  var items = [1, 2, 3, 4, 5];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: items.length,
        itemBuilder: (context, index) {
          final id = items[index];
          return GestureDetector(
            onTap: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (context) => ItemDetailPage(id)));
            },
            child: ItemTile(
              id,
              key: UniqueKey(),
            ),
          );
        },
      ),
    );
  }
}

class ItemTile extends StatefulWidget {
  final int id;

  ItemTile(this.id, {Key key}) : super(key: key);

  @override
  _ItemTileState createState() => _ItemTileState();
}

class _ItemTileState extends State<ItemTile> {
  bool _imageIsLoaded = false;

  _ItemTileState();

  @override
  Widget build(BuildContext context) {
    return _imageIsLoaded
        ? Text('Loaded')
        : Hero(
            tag: 'id-${widget.id}',
            child: TransitionToImage(
              image: AdvancedNetworkImage(
                'https://www.gstatic.com/webp/gallery/1.jpg',
                loadedCallback: () {
                  print(mounted);
                  //if(mounted) {
                  setState(() {
                    _imageIsLoaded = true;
                  });
                  //}
                },
              ),
            ),
          );
  }
}

class ItemDetailPage extends StatefulWidget {
  final int id;

  ItemDetailPage(this.id);

  @override
  _ItemDetailPageState createState() => _ItemDetailPageState();
}

class _ItemDetailPageState extends State<ItemDetailPage> {
  @override
  Widget build(BuildContext context) {
    return Hero(
      tag: 'id-${widget.id}',
      child: TransitionToImage(
        image: AdvancedNetworkImage(
          'https://www.gstatic.com/webp/gallery/1.jpg',
        ),
      ),
    );
  }
}
```

**Comment by mchome** [comment]
Hmmm, i have no crashes with this example but only one `Loaded` widget was showed bacause of flutter's memory image cache. Try to add `retryLimit: widget.id` in `_ItemTileState`'s `AdvancedNetworkImage`.

**Comment by erf** [comment]
If i run the app once, and then perform a hot restart, it crashes with the following ( trying to set state when it has been disposed ).
```
setState() called after dispose(): _ItemTileState#82c5b(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
```
Adding `retryLimit`, makes it work, but i'm not sure what it does or why setting the `widget.id` to it makes sense..

**Comment by mchome** [comment]
Just making a different image provider hashes.

**Comment by erf** [comment]
It feels a bit wrong to set `retryLimit`, just to make a different hash, when i don't care about `retryLimit`. Maybe passing a `UniqueKey` would be better? I still don't understand though why the `AdvancedNetworkImage` is disposed in `loadedCallback`.

**Comment by mchome** [comment]
Umm, maybe i can add `uid` to make different hashes.
```dart
@override
int get hashCode => ui.hashValues(uid, url, scale, header, useDiskCache,
    retryLimit, retryDuration, retryDurationFactor, timeoutDuration);
```
`AdvancedNetworkImage` is not widget, it was `_ItemTileState#82c5b` disposed, and `loadedCallback` fired. You can add `if (mounted)` or remove `setState`.

**Comment by erf** [comment]
How would the `uid` be created?

If i add `if (mounted)`, the `Loaded` text is not shown. Do you know why the `_ItemTileState` is disposed?

**Comment by mchome** [comment]
Next version maybe?

Maybe `ListBuilder` fired dispose(), i do not have this problem actually.

**Comment by erf** [comment]
What i optimally would like to happen is that `loadedCallback` is called after image is loaded ( whether it is cached or not ), and that i then can call `setState` to rebuild the UI, without having to set some `retryLimit` or `uid` variable, and optimally without having to check if it is mounted, because it should be.. i think.

As you said, you were not able to show the `loaded` text after image is loaded, so i think that is a problem still for you.

**Comment by chrispypatt** [comment]
Similar to the issue above, I have a AdvancedNetworkImage which does not use loadedCallback but instead uses an icon for loadingWidget and I get the same setState assertion only in Hero widgets (works fine with MaterialScaffold but has issues with CupertinoScaffold. Removing the loading widget eliminates the assertion.

```
TransitionToImage(
    image: AdvancedNetworkImage(
        widget.deal.photo,
        useDiskCache: true,
            cacheRule: CacheRule(maxAge: const Duration(days: 1)),
         ),
         fit: BoxFit.cover,
         loadingWidget: Container(
             color: Colors.transparent,
             child: const Icon(Icons.local_dining, 
                 color: Colors.white,
                 size: 150.0,
              ),
           ),                    
      ),
),
` ``

**Comment by tamoyal** [comment]
I have the same problem as @erf and the `loadedFromDiskCacheCallback` is never fired when the image is loaded from the cache. So it works fine on first load to rebuild the UI based on a state change but the second time, there is no callback to tell me the image was loaded from cache so my UI never updates

**Comment by tamoyal** [comment]
Adding this works. So basically we don't get loaded callbacks when images are loaded from the memory cache
```
                useDiskCache: true,
                disableMemoryCache: true,
```
